"""Add metal_prices table

Revision ID: 908f022d3547
Revises: c1a98996ca56
Create Date: 2025-10-28 22:19:00.575733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908f022d3547'
down_revision: Union[str, Sequence[str], None] = 'c1a98996ca56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metal', sa.Enum('SILVER', 'GOLD', name='metal'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metal_prices_metal_created_at', 'metal_prices', ['metal', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metal_prices_metal_created_at', table_name='metal_prices')
    op.drop_table('metal_prices')
    # ### end Alembic commands ###
