[project]
name = "masstimes"
version = "0.1.0"
description = "See mass times or other church events for different churches."
readme = "README.md"
authors = [
    { name = "Christian Paling", email = "christian.paling@googlemail.com" }
]
requires-python = ">=3.14.2"
dependencies = [
    "alembic==1.18.3",
    "beautifulsoup4==4.14.3",
    "fastapi[standard]==0.128.0",
    "httpx==0.28.1",
    "jinja2==3.1.6",
    "mistralai==1.11.1",
    "python-dotenv>=1.2.1",
    "sqlalchemy==2.0.46",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
    "ruff==0.14.14",
    "ty==0.0.14",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.uv]
required-version = ">=0.9.26"

[tool.ruff]
lint.select = ["E", "F", "I", "ANN"]
