name: Masstimes

on:
  push:
    branches:
      - "**"
    paths:
      - "masstimes/**"
      - ".github/workflows/masstimes.yml"

defaults:
  run:
    working-directory: ./masstimes

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies (including dev)
        run: uv sync --all-groups --locked

      - name: Type check
        run: uv run mypy .

      - name: Lint
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --check
